Learn 587
betrybe/blocked-files-checkout-action pull request #1
Opened 2021-01-06 22:26 UTC by eucleciojosias

2021-01-07 12:23 UTC, hurrycaner approved these changes

2021-01-07 12:29 UTC, eucleciojosias commented on README.md
> +#### `restore_branch` **(obrigaório)**
```suggestion
#### `restore_branch` **(obrigatório)**
```

2021-01-07 13:43 UTC, caironoleto requested changes

2021-01-07 13:43 UTC, caironoleto commented on entrypoint.sh
> +  git restore --source origin/master -- "$file"
aqui fixa que a branch `master` vai ser sempre a branch principal, o que não deveria ser.

2021-01-07 13:45 UTC, caironoleto commented
@eucleciojosias uma das premissas do nosso time de desenvolvimento é que podemos pedir code review pra qualquer pessoa da trybe, é super importante que os pull requests tenham um bom nível de contexto no título e descrição, isso facilita a vida de quem vai fazer code review.

2021-01-07 13:57 UTC, jeanpsv requested changes

2021-01-07 13:57 UTC, jeanpsv commented on README.md
> +Github Action que restaura uma lista de arquivos da branch principal do repositório do projeto. Estes arquivos não podem ser alterados pelo estudante e são definidos no arquivo `trybe.yml` com a chav
```suggestion
Github Action que restaura uma lista de arquivos da branch principal do repositório do projeto. Estes arquivos não podem ser alterados pela pessoa estudante e são definidos no arquivo `trybe.yml` com a chave `ignore_files`.
```

2021-01-07 13:57 UTC, jeanpsv commented on README.md
> +Para definir quais arquivos devem ser restaurados para desfazer as alteracões do estudante é necessário adicionar o diretório ou o caminho do arquivo no `trybe.yml` conforme exemplo abaixo:
```suggestion
Para definir quais arquivos devem ser restaurados para desfazer as alteracões da pessoa estudante é necessário adicionar o diretório ou o caminho do arquivo no `trybe.yml` conforme exemplo abaixo:
```

2021-01-07 14:39 UTC, eucleciojosias commented
@caironoleto eu deixei o link do card do JIRA na descrição da PR para dar contexto, mas posso melhorar isso copiando a descrição da tarefa aqui na PR tb.

2021-01-07 14:41 UTC, jeanpsv requested changes

2021-01-07 14:41 UTC, jeanpsv commented on README.md
> +Para definir quais arquivos devem ser restaurados para desfazer as alteracões do estudante é necessário adicionar o diretório ou o caminho do arquivo no `trybe.yml` conforme exemplo abaixo:
@eucleciojosias tem mais um aqui

2021-01-07 14:44 UTC, jeanpsv approved these changes

2021-01-08 12:05 UTC, caironoleto approved these changes

2021-01-12 17:06 UTC, merged